default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# Desenvolvimento
development:
  <<: *default
  database: ecommerce_aliadoshop_development
  username: postgres
  password: asdpoi04
  host: localhost
  port: 5432
# Testes
test:
  <<: *default
  database: ecommerce_aliadoshop_test
  username: postgres
  password: asdpoi04
  host: localhost
  port: 5432

production:
  <<: *default
  database: ecommerce_aliadoshop_production
  username: postgres
  password: <%= ENV["ECOMMERCE_ALIADOSHOP_DATABASE_PASSWORD"] %>
